version: '3.1'

services:
  server:
    container_name: server
    restart: always
    tty: true
    image: kochurovro/circleci-hw-docker:0.1.14
    ports:
      - "8080:8080"
    logging:
      driver: json-file
      options:
        max-size: "150m"
        max-file: "5"
