version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/kochurovro/circleci-hw
    steps:
      - checkout
      - run:
          name: Setup Env
          command: |
            echo ${PROJECT_PATH}
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=circleci-hw-docker' >> $BASH_ENV 
      - run: go get -v -t -d ./...
      - run: go test -v ./...

  build: 
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/kochurovro/circleci-hw
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - $FINGER_PRINT
      - setup_remote_docker
      - run:
          name: Setup Env
          command: |
            echo ${PROJECT_PATH}
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=circleci-hw-docker' >> $BASH_ENV 
      - run:
          name: Build and push Docker image
          command: |
            docker build -t kochurovro/$IMAGE_NAME:$TAG .
            mkdir docker-image
            docker save -o docker-image/image.tar kochurovro/$IMAGE_NAME:$TAG 
      - persist_to_workspace:
          root: .
          paths:
            - docker-image           
            # docker ps -a
            # echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            # docker push $DOCKER_LOGIN/$IMAGE_NAME:$TAG  
  
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: workspace
  #     - run:
  #         name: Setup Env
  #         command: |
  #           echo ${PROJECT_PATH}
      - run:
          name: Load image
          command: |
            docker load --input workspace/docker-image/image.tar 
      - run:
          name: Deploy to S3
          command: |
            sudo apt-get install awscli
            aws configure set default.s3.signature_version s3v4
            aws s3 sync workspace/docker-image/image.tar s3://circleci-hw/ 
  #           # # # docker ps -a
  #           # # aws s3 cp $HOME/project/ s3://circleci-hw/
            
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      # - deploy
